at_exit {
  puts "Error!"
}

abort "Something wrong!"